---
get_products:
  - context
  - pge_config
  - sys_config

get_metadata:
  - context
  - pge_config.get(constants.GET_METADATA_KEY).get('keys')

get_orbit_info:
  - job_params.get(constants.HALF_ORBIT_ID_KEY, None)

getEclipseTimes:
  - job_params.get(product_metadata.ORBIT_NUMBER_METADATA) # orbit number
  - job_params.get(product_metadata.ORBIT_DIRECTION_METADATA) # orbit direction

get_info1:
  - job_params
  - pge_config

get_info2:
  - context
  - pge_config

